; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:ATmega328P]
; platform = atmelavr
; board = ATmega328P
; framework = arduino

[env:atmega328p_xplained_mini]
platform = atmelavr
board = atmega328p_xplained_mini
framework = arduino

; Viteza de comunicare cu laptopul
monitor_speed = 9600

build_flags =
  ; Aceasta linie permite printf sa afiseze numere cu virgula (ex: 10.50 lei)
  -Wl,-u,vfprintf -lprintf_flt -lm
  -DDEMO_BAUD=9600UL

; Pastreaza setarea de EEPROM pentru a nu pierde banii la fiecare upload
board_hardware.eesave = yes
lib_deps = marcoschwartz/LiquidCrystal_I2C@^1.1.4